# Generated by Django 5.2.4 on 2025-08-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_images/')),
                ('location', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=100)),
                ('date_found', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_images/')),
                ('location', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=100)),
                ('date_lost', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Documents', 'Documents'), ('Stationery', 'Stationery'), ('Accessories', 'Accessories'), ('Personal Items', 'Personal Items')], max_length=50)),
                ('location', models.CharField(choices=[('Canteen', 'Canteen'), ('Library', 'Library'), ('Main Gate', 'Main Gate'), ('Parking', 'Parking'), ('A Block', 'A Block'), ('B Block', 'B Block'), ('C Block', 'C Block'), ('Ground', 'Ground'), ('Staircase', 'Staircase')], max_length=200)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
