# Generated by Django 5.2.4 on 2025-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Documents', 'Documents'), ('Stationery', 'Stationery'), ('Accessories', 'Accessories'), ('Personal Items', 'Personal Items')], default='Personal Items', max_length=50),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Documents', 'Documents'), ('Stationery', 'Stationery'), ('Accessories', 'Accessories'), ('Personal Items', 'Personal Items')], default='Personal Items', max_length=50),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='location',
            field=models.CharField(choices=[('Canteen', 'Canteen'), ('Library', 'Library'), ('Main Gate', 'Main Gate'), ('Parking', 'Parking'), ('A Block', 'A Block'), ('B Block', 'B Block'), ('C Block', 'C Block'), ('Ground', 'Ground'), ('Staircase', 'Staircase')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='location',
            field=models.CharField(choices=[('Canteen', 'Canteen'), ('Library', 'Library'), ('Main Gate', 'Main Gate'), ('Parking', 'Parking'), ('A Block', 'A Block'), ('B Block', 'B Block'), ('C Block', 'C Block'), ('Ground', 'Ground'), ('Staircase', 'Staircase')], max_length=100),
        ),
    ]
