# Generated by Django 5.2.4 on 2025-08-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_founditem_category_lostitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='location',
            field=models.CharField(choices=[('Left Parking', 'Left Parking'), ('Right Parking', 'Right Parking'), ('Inner Parking', 'Inner Parking'), ('Main Gate', 'Main Gate'), ('Fountain', 'Fountain'), ('Garden', 'Garden'), ('A Block', 'A Block'), ('B Block', 'B Block'), ('C Block', 'C Block'), ('Auditorium', 'Auditorium'), ('D Block', 'D Block'), ('E Block', 'E Block'), ('Canteen', 'Canteen'), ('Library', 'Library'), ('SISTK-A Block', 'SISTK-A Block'), ('SISTK-B Block', 'SISTK-B Block'), ('Office Room', 'Office Room'), ('Examination Cell', 'Examination Cell'), ('Mechanical Workshop', 'Mechanical Workshop'), ('SISTK-Mechanical Workshop', 'SISTK-Mechanical Workshop'), ('Yoga hall', 'Yoga hall'), ('GYM', 'GYM'), ('Telugu-Girls hostel', 'Telugu-Girls hostel'), ('Bihar-Girls hostel', 'Bihar-Girls hostel'), ('Telugu-Boys hostel', 'Telugu-Boys hostel'), ('Bihar-Boys hostel', 'Bihar-Boys hostel'), ('Play Ground-FootBall', 'Play Ground-FootBall'), ('Play Ground-BasketBall', 'Play Ground-BasketBall')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='location',
            field=models.CharField(choices=[('Left Parking', 'Left Parking'), ('Right Parking', 'Right Parking'), ('Inner Parking', 'Inner Parking'), ('Main Gate', 'Main Gate'), ('Fountain', 'Fountain'), ('Garden', 'Garden'), ('A Block', 'A Block'), ('B Block', 'B Block'), ('C Block', 'C Block'), ('Auditorium', 'Auditorium'), ('D Block', 'D Block'), ('E Block', 'E Block'), ('Canteen', 'Canteen'), ('Library', 'Library'), ('SISTK-A Block', 'SISTK-A Block'), ('SISTK-B Block', 'SISTK-B Block'), ('Office Room', 'Office Room'), ('Examination Cell', 'Examination Cell'), ('Mechanical Workshop', 'Mechanical Workshop'), ('SISTK-Mechanical Workshop', 'SISTK-Mechanical Workshop'), ('Yoga hall', 'Yoga hall'), ('GYM', 'GYM'), ('Telugu-Girls hostel', 'Telugu-Girls hostel'), ('Bihar-Girls hostel', 'Bihar-Girls hostel'), ('Telugu-Boys hostel', 'Telugu-Boys hostel'), ('Bihar-Boys hostel', 'Bihar-Boys hostel'), ('Play Ground-FootBall', 'Play Ground-FootBall'), ('Play Ground-BasketBall', 'Play Ground-BasketBall')], max_length=100),
        ),
        migrations.AlterField(
            model_name='searchitem',
            name='location',
            field=models.CharField(choices=[('Left Parking', 'Left Parking'), ('Right Parking', 'Right Parking'), ('Inner Parking', 'Inner Parking'), ('Main Gate', 'Main Gate'), ('Fountain', 'Fountain'), ('Garden', 'Garden'), ('A Block', 'A Block'), ('B Block', 'B Block'), ('C Block', 'C Block'), ('Auditorium', 'Auditorium'), ('D Block', 'D Block'), ('E Block', 'E Block'), ('Canteen', 'Canteen'), ('Library', 'Library'), ('SISTK-A Block', 'SISTK-A Block'), ('SISTK-B Block', 'SISTK-B Block'), ('Office Room', 'Office Room'), ('Examination Cell', 'Examination Cell'), ('Mechanical Workshop', 'Mechanical Workshop'), ('SISTK-Mechanical Workshop', 'SISTK-Mechanical Workshop'), ('Yoga hall', 'Yoga hall'), ('GYM', 'GYM'), ('Telugu-Girls hostel', 'Telugu-Girls hostel'), ('Bihar-Girls hostel', 'Bihar-Girls hostel'), ('Telugu-Boys hostel', 'Telugu-Boys hostel'), ('Bihar-Boys hostel', 'Bihar-Boys hostel'), ('Play Ground-FootBall', 'Play Ground-FootBall'), ('Play Ground-BasketBall', 'Play Ground-BasketBall')], max_length=200),
        ),
    ]
