# Generated by Django 5.2.4 on 2025-08-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_founditem_location_alter_lostitem_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LostItem',
        ),
    ]
